//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaVerity.UI.PedidosServico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pedido", Namespace="http://servicos.verity.com/1.0/Entidades")]
    [System.SerializableAttribute()]
    public partial class Pedido : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DataPedidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LojaVerity.UI.PedidosServico.PedidoLinha[] LinhasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoTotalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cliente {
            get {
                return this.ClienteField;
            }
            set {
                if ((object.ReferenceEquals(this.ClienteField, value) != true)) {
                    this.ClienteField = value;
                    this.RaisePropertyChanged("Cliente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DataPedido {
            get {
                return this.DataPedidoField;
            }
            set {
                if ((this.DataPedidoField.Equals(value) != true)) {
                    this.DataPedidoField = value;
                    this.RaisePropertyChanged("DataPedido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LojaVerity.UI.PedidosServico.PedidoLinha[] Linhas {
            get {
                return this.LinhasField;
            }
            set {
                if ((object.ReferenceEquals(this.LinhasField, value) != true)) {
                    this.LinhasField = value;
                    this.RaisePropertyChanged("Linhas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecoTotal {
            get {
                return this.PrecoTotalField;
            }
            set {
                if ((this.PrecoTotalField.Equals(value) != true)) {
                    this.PrecoTotalField = value;
                    this.RaisePropertyChanged("PrecoTotal");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PedidoLinha", Namespace="http://servicos.verity.com/1.0/Entidades")]
    [System.SerializableAttribute()]
    public partial class PedidoLinha : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long PedidoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ProdutoIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantidadeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long PedidoID {
            get {
                return this.PedidoIDField;
            }
            set {
                if ((this.PedidoIDField.Equals(value) != true)) {
                    this.PedidoIDField = value;
                    this.RaisePropertyChanged("PedidoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ProdutoID {
            get {
                return this.ProdutoIDField;
            }
            set {
                if ((this.ProdutoIDField.Equals(value) != true)) {
                    this.ProdutoIDField = value;
                    this.RaisePropertyChanged("ProdutoID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantidade {
            get {
                return this.QuantidadeField;
            }
            set {
                if ((this.QuantidadeField.Equals(value) != true)) {
                    this.QuantidadeField = value;
                    this.RaisePropertyChanged("Quantidade");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicos.verity.com/1.0", ConfigurationName="PedidosServico.IPedidosServico")]
    public interface IPedidosServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IPedidosServico/CriarPedido", ReplyAction="http://servicos.verity.com/1.0/IPedidosServico/CriarPedidoResponse")]
        LojaVerity.UI.PedidosServico.Pedido CriarPedido(LojaVerity.UI.PedidosServico.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IPedidosServico/CriarPedido", ReplyAction="http://servicos.verity.com/1.0/IPedidosServico/CriarPedidoResponse")]
        System.Threading.Tasks.Task<LojaVerity.UI.PedidosServico.Pedido> CriarPedidoAsync(LojaVerity.UI.PedidosServico.Pedido pedido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedidos", ReplyAction="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedidosResponse")]
        LojaVerity.UI.PedidosServico.Pedido[] BuscarPedidos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedidos", ReplyAction="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedidosResponse")]
        System.Threading.Tasks.Task<LojaVerity.UI.PedidosServico.Pedido[]> BuscarPedidosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedido", ReplyAction="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedidoResponse")]
        LojaVerity.UI.PedidosServico.Pedido BuscarPedido(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedido", ReplyAction="http://servicos.verity.com/1.0/IPedidosServico/BuscarPedidoResponse")]
        System.Threading.Tasks.Task<LojaVerity.UI.PedidosServico.Pedido> BuscarPedidoAsync(string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPedidosServicoChannel : LojaVerity.UI.PedidosServico.IPedidosServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosServicoClient : System.ServiceModel.ClientBase<LojaVerity.UI.PedidosServico.IPedidosServico>, LojaVerity.UI.PedidosServico.IPedidosServico {
        
        public PedidosServicoClient() {
        }
        
        public PedidosServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LojaVerity.UI.PedidosServico.Pedido CriarPedido(LojaVerity.UI.PedidosServico.Pedido pedido) {
            return base.Channel.CriarPedido(pedido);
        }
        
        public System.Threading.Tasks.Task<LojaVerity.UI.PedidosServico.Pedido> CriarPedidoAsync(LojaVerity.UI.PedidosServico.Pedido pedido) {
            return base.Channel.CriarPedidoAsync(pedido);
        }
        
        public LojaVerity.UI.PedidosServico.Pedido[] BuscarPedidos() {
            return base.Channel.BuscarPedidos();
        }
        
        public System.Threading.Tasks.Task<LojaVerity.UI.PedidosServico.Pedido[]> BuscarPedidosAsync() {
            return base.Channel.BuscarPedidosAsync();
        }
        
        public LojaVerity.UI.PedidosServico.Pedido BuscarPedido(string id) {
            return base.Channel.BuscarPedido(id);
        }
        
        public System.Threading.Tasks.Task<LojaVerity.UI.PedidosServico.Pedido> BuscarPedidoAsync(string id) {
            return base.Channel.BuscarPedidoAsync(id);
        }
    }
}
