//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaVerity.Modelo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VerityEntidades : DbContext
    {
        public VerityEntidades()
            : base("name=VerityEntidades")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pedido> Pedidos { get; set; }
        public virtual DbSet<PedidoLinha> PedidoLinhas { get; set; }
        public virtual DbSet<Produto> Produtos { get; set; }
    }
}
