//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaVerity.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoLinha
    {
        public long ID { get; set; }
        public long PedidoID { get; set; }
        public long ProdutoID { get; set; }
        public int Quantidade { get; set; }
        public decimal Preco { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
