//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LojaVerity.UI.ProdutosServico {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Produto", Namespace="http://servicos.verity.com/1.0/Entidades")]
    [System.SerializableAttribute()]
    public partial class Produto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescricaoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descricao {
            get {
                return this.DescricaoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescricaoField, value) != true)) {
                    this.DescricaoField = value;
                    this.RaisePropertyChanged("Descricao");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Preco {
            get {
                return this.PrecoField;
            }
            set {
                if ((this.PrecoField.Equals(value) != true)) {
                    this.PrecoField = value;
                    this.RaisePropertyChanged("Preco");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://servicos.verity.com/1.0", ConfigurationName="ProdutosServico.IProdutosServico")]
    public interface IProdutosServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/BuscarProdutos", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/BuscarProdutosResponse")]
        LojaVerity.UI.ProdutosServico.Produto[] BuscarProdutos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/BuscarProdutos", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/BuscarProdutosResponse")]
        System.Threading.Tasks.Task<LojaVerity.UI.ProdutosServico.Produto[]> BuscarProdutosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/BuscarProduto", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/BuscarProdutoResponse")]
        LojaVerity.UI.ProdutosServico.Produto BuscarProduto(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/BuscarProduto", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/BuscarProdutoResponse")]
        System.Threading.Tasks.Task<LojaVerity.UI.ProdutosServico.Produto> BuscarProdutoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/ExcluirProduto", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/ExcluirProdutoResponse")]
        void ExcluirProduto(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/ExcluirProduto", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/ExcluirProdutoResponse")]
        System.Threading.Tasks.Task ExcluirProdutoAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/CadastrarProduto", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/CadastrarProdutoResponse")]
        LojaVerity.UI.ProdutosServico.Produto CadastrarProduto(LojaVerity.UI.ProdutosServico.Produto produto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://servicos.verity.com/1.0/IProdutosServico/CadastrarProduto", ReplyAction="http://servicos.verity.com/1.0/IProdutosServico/CadastrarProdutoResponse")]
        System.Threading.Tasks.Task<LojaVerity.UI.ProdutosServico.Produto> CadastrarProdutoAsync(LojaVerity.UI.ProdutosServico.Produto produto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProdutosServicoChannel : LojaVerity.UI.ProdutosServico.IProdutosServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosServicoClient : System.ServiceModel.ClientBase<LojaVerity.UI.ProdutosServico.IProdutosServico>, LojaVerity.UI.ProdutosServico.IProdutosServico {
        
        public ProdutosServicoClient() {
        }
        
        public ProdutosServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutosServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LojaVerity.UI.ProdutosServico.Produto[] BuscarProdutos() {
            return base.Channel.BuscarProdutos();
        }
        
        public System.Threading.Tasks.Task<LojaVerity.UI.ProdutosServico.Produto[]> BuscarProdutosAsync() {
            return base.Channel.BuscarProdutosAsync();
        }
        
        public LojaVerity.UI.ProdutosServico.Produto BuscarProduto(string id) {
            return base.Channel.BuscarProduto(id);
        }
        
        public System.Threading.Tasks.Task<LojaVerity.UI.ProdutosServico.Produto> BuscarProdutoAsync(string id) {
            return base.Channel.BuscarProdutoAsync(id);
        }
        
        public void ExcluirProduto(string id) {
            base.Channel.ExcluirProduto(id);
        }
        
        public System.Threading.Tasks.Task ExcluirProdutoAsync(string id) {
            return base.Channel.ExcluirProdutoAsync(id);
        }
        
        public LojaVerity.UI.ProdutosServico.Produto CadastrarProduto(LojaVerity.UI.ProdutosServico.Produto produto) {
            return base.Channel.CadastrarProduto(produto);
        }
        
        public System.Threading.Tasks.Task<LojaVerity.UI.ProdutosServico.Produto> CadastrarProdutoAsync(LojaVerity.UI.ProdutosServico.Produto produto) {
            return base.Channel.CadastrarProdutoAsync(produto);
        }
    }
}
